config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'posts/about'
  get 'posts/user_info'
  devise_for :users
  resources :posts do
    resources :comments
    member do
      put "like", to: "posts#like"
      put "unlike", to: "posts#unlike"
    end
  end
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    attr_accessor :image
    has_attached_file :image, :styles => { :orginal => "", :medium => "500x500>", :thumb => "350x350>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
    
    belongs_to :user
    has_many :comments
    has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :image
  has_attached_file :image, styles: { orginal: "",medium: "300x300",thumb: "80x80",mini: "25x25" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  has_many :posts
  has_many :comments
  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale 
  before_action :configure_permitted_parameters, if: :devise_controller? 
  
  def set_locale
    I18n.locale=params[:locale] || I18n.default_locale  
    Rails.application.routes.default_url_options[:locale]= I18n.locale
  end
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name,:surname,:image])
      devise_parameter_sanitizer.permit(:account_update,keys:[:name,:surname,:image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :denetim]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post
  before_action :denetim, only: [:edit,:destroy]
  
  def denetim
    unless @comments.user_id==current_user.id
      redirect_to post_url(params[:post_id]),notice:"Bu Kayıt Üzerinde İşlem Yapabilmek İçin Yetkiniz Bulunmamaktadır."
    end
  end
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = @post.comments.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = @post.comments.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @post.comments.build(comment_params)
    @comment.user= current_user
  
    respond_to do |format|
      if @comment.save
        format.js
        format.html { redirect_to post_url(params[:post_id]), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    @comments = Comment.find(params[:id])
    @comments.bdy=comment_params[:bdy]
    @comments.save
    respond_to do |format|
      if @comments.save
        format.html { redirect_to post_url(params[:post_id]), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    Comment.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to post_url(params[:post_id]), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post=Post.find(params[:post_id])
      #@comment = @post.comments.find(params[:id])
    end

    def set_comment
      @comments = Comment.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:bdy)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy,:denetim,:like, :unlike]
  before_action :authenticate_user!, except: [:index, :show,:about]
  before_action :denetim, only: [:edit,:destroy]
  
  def like
    @l=Like.new
    @l.post=@post
    @l.user=current_user
    @l.save
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end

  def unlike
    @l=Like.where(post:@post,user:current_user).first
    @l.destroy
    respond_to do |format|
      format.js {render layout: false}
      format.json
    end
  end
  
  def denetim
    unless @post.user==current_user
      redirect_to root_path,notice:"Bu Kayıt Üzerinde İşlem Yapabilmek İçin Yetkiniz Bulunmamaktadır."
    end
  end
  
  # GET /posts
  # GET /posts.json
  def index
    
    if params[:user]
      @posts = Post.where(user: params[:user]).order("created_at DESC")
    else
       @posts = Post.all.order("created_at DESC")
    end
    
    @posts = Post.all
  end
  
  def about
  end
  
  # GET /posts/1
  # GET /posts/1.json
  def show
    @likeds=Like.where(post: @post).all
    @comments=@post.comments.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user=current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Gönderiniz başarıyla oluşturuldu...' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Gönderiniz başarıyla güncellendi...' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.comments.destroy_all
    @post.likes.destroy_all
    respond_to do |format|
      if @post.destroy
        format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to posts_url, notice: 'Post was not destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :msg, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_editform.html.erb
<%= form_for([@post, @comment=Comment.find(params[:id])]) do |f| %>
<h1><%=t("e_comment")%></h1>
<div class="container kayit_sergile" style="border-color:red">
  <div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
      <%=image_tag @post.user.image.url(:thumb),:class => 'img-circle' if @post.user.image?%> 
      <%=@post.user.name%> <%=@post.user.surname%> 
      <%=@post.created_at%>
    </div>
  </div>
  <% if @post.title!=""%>
    <br>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <b><%=@post.title%></b>
      </div>
    </div>
    <br>
  <% end %>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding:5%;">
      <% if @post.image? %>
        <%= image_tag @post.image.url(:thumb), :class => 'img-rounded', :style => 'display:block;margin:auto;' %>
      <% else %>
        <strong>Bu gönderide resim bulunmamaktadır.</strong>
      <%end%>
    </div>
  </div>
  <% if @post.title!=""%>
  <br>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <%=@post.msg%>
      </div>
    </div>
    <br>
  <% end %>
  <div class="row" style="padding:1%">
      <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
        <%=image_tag @comment.user.image.url(:mini),style:"border-radius:1em;" if @comment.user.image?%>
      </div>
      
      <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <b>
              <%=@comment.user.name%> <%=@comment.user.surname%>
            </b>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <%= f.text_field :bdy, id: :comment_bdy, class:"form-control",style:"width:100%;border-color:red;color:black" %>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <x>
                <% if user_signed_in? %>
                  <% if current_user.id==@comment.user_id %>
                  <input type="submit" name="commit" value="<%=t("e_comment")%>" style="border-radius:0;">
                    <a></a>
                    <a></a>
                    <a data-confirm="<%=t("p_data_confirm")%>?" rel="nofollow" data-method="delete" 
                    href="/posts/<%=@post.id%>/comments/<%=@comment.id%>?locale=<%= I18n.locale %>" style="text-decoration: none;padding:0.5%;border:0;">
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                  <% end %>
                <% end %>
            </x>
          </div>
        </div>
      </div>
  </div>
</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for([@post, Comment.new], :remote=>'true', :controller => 'comments', :action => 'create') do |f| %>
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="padding:1%;display: inline;">
            <%= f.text_field :bdy, id: :comment_bdy, class:"form-control",style:"width:100%;" %>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="padding:1.5%;">
        <input type="submit" name="commit" value="<%=t("s_comment")%>" style="border-radius:0;">
    </div>
</div>
<% end %>

app/views/comments/create.js.erb
$('#comments').append('<div class="row"><div class="col-xs-12 col-sm-12 col-md-1 col-lg-1"><%=image_tag @comment.user.image.url(:mini),style:"border-radius:1em;" if @comment.user.image? %></div><div class="col-xs-12 col-sm-12 col-md-11 col-lg-11"><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><b><%=@comment.user.name%> <%=@comment.user.surname%></b></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><%=@comment.bdy%></div></div><div class="row"><div class="col-xs-12 col-sm-12 col-md-12 col-lg-12"><x><a href="/posts/<%=@comment.post.id%>/comments/<%=@comment.id%>?locale=<%= I18n.locale %>" style="text-decoration: none;padding:0.5%;border:0;" class="fa fa-eye"></a><a href="/posts/<%=@comment.post.id%>/comments/<%=@comment.id%>/edit?locale=<%= I18n.locale %>"  style="text-decoration: none;padding:0.5%;border:0;"> <i class="fa fa-pencil fa-lg" aria-hidden="true"></i></a><a data-confirm="<%=t("p_data_confirm")%>?" rel="nofollow" data-method="delete" href="/posts/<%=@comment.post.id%>/comments/<%=@comment.id%>?locale=<%= I18n.locale %>" style="text-decoration: none;padding:0.5%;border:0;"><i class="fa fa-trash" aria-hidden="true"></i></a></x></div></div></div></div><br>');

app/views/comments/edit.html.erb
<div class="container" style="width:100%;">
    <%= render 'editform', comment: @comment %>
</div>

app/views/comments/index.html.erb
<table>
  <thead>
    <tr>
      <th>Yorum Sahibi</th>
      <th>Yorum</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.name %> <%= comment.user.surname %></td>
        <td><%= comment.bdy %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/new.html.erb
<%= render 'form' , comment: @comment %>

app/views/comments/show.html.erb
<h1><%=t("show_comment")%></h1>
<%= form_for([@post,@comment=Comment.find(params[:id])]) do |f| %>  
<div class="container kayit_sergile">
  <div class="row" style="padding:1%">
      <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
        <%=image_tag @comment.user.image.url(:mini),style:"border-radius:1em;" if @comment.user.image?%>
      </div>
      
      <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <b>
              <%=@comment.user.name%> <%=@comment.user.surname%>
            </b>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12" style="padding-top:2.5%">
            <%=@comment.bdy%>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <x>
                <% if user_signed_in? %>
                  <% if current_user.id==@comment.user_id %>
                    <a></a>
                    <a href="/posts/<%=@post.id%>/comments/<%=@comment.id%>/edit?locale=<%= I18n.locale %>"  style="text-decoration: none;padding:0.5%;border:0;"> 
                        <i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
                    </a>
                    <a data-confirm="<%=t("p_data_confirm")%>?" rel="nofollow" data-method="delete" 
                    href="/posts/<%=@post.id%>/comments/<%=@comment.id%>?locale=<%= I18n.locale %>" style="text-decoration: none;padding:0.5%;border:0;">
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    </a>
                  <% end %>
                <% end %>
            </x>
          </div>
        </div>
      </div>
  </div>
</div>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <title>mujde.akif@gmail.com</title>
  <link rel="Shortcut Icon"  href="http://icons.veryicon.com/ico/Internet%20%26%20Web/Rounded%20Flat%20Social/share.ico"  type="image/x-icon">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse" style="border-radius:0;">
    <%= render 'shared/navbar' %>
  </nav>
  
  <main class="container bg" style="width:100%;padding-top:0.5%;overflow:auto;">
    
    <div data-toggle="tooltip" data-placement="top" title="<%=t("ad_slot")%>." class="hidden-xs hidden-sm col-md-2 col-lg-2">
      <img src="https://pbs.twimg.com/media/DMra0X8V4AAQXpK.jpg" width="100%">
    </div>
    
    <div class="col-md-12 col-sm-12 col-md-8 col-lg-8" style="height:100%;">
      <%= yield %>
    </div>
    
    <div data-toggle="tooltip" data-placement="top" title="<%=t("ad_slot")%>." class="hidden-xs hidden-sm col-md-2 col-lg-2">
      <img src="http://www.parismiki.com.sg/wp-content/uploads/2017/03/7a899515b4d4c7bcd332e1449308a58a.jpg" width="100%">
      <hr>
      <img src="http://2.bp.blogspot.com/-gMWE8DaJT_c/VPRkp5prWHI/AAAAAAAAAQk/cqzsuw8M1KA/s1600/isirilmis-elmanin-sirri--1587217.Jpeg" width="100%">
    </div>
    
  </main>
  <div class="footer container">
    <%= render 'shared/footerbar' %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<div class="container kayit_sergile" style="padding:1%;">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <script>
    $(document).ready(function(){
      $('#post_title').val("<%= @post.title%>");
    });
  </script>
  <div class="media">
    <div class="media-left media-top">
      
    </div>
    <div class="media-body ">
      <div class="media-heading">
        <label><%=t("img")%></label><br><br>
        <% if @post.image? %>
          <%= image_tag @post.image.url(:thumb) %><br><br>
        <%end%>
        <%= f.file_field :image%>
      </div>
      <hr>
      <div class="form">
        <b><%=t("title")%></b>
        <br><br>
        <input type="text" name="post[title]" id="post_title" class="form-control" style="width:100%;">
      </div>
      <hr>
      <div id="1">
        <b><%=t("content")%></b>
        <br><br>
        <textarea class="form-control" rows="7" id="post_msg" name="post[msg]" style="resize:none;color:black;background-color:white;border-color:lightblue;"><%=@post.msg%></textarea>
      </div>
      <hr>
      <div style="text-align:right;">
        <input type="submit" name="commit" class="" value="<%=t("send")%>!" style="border-radius:0;">
      </div>
    </div>
  </div>
<% end %>

app/views/posts/about.html.erb
<style>
    li{
        color:black;
    }
</style>
<h1>Site <%=t("about")%></h1>
<div class="panel panel-primary" style="text-align:left">
    <div class="panel-body">
        <ol>
            <br>
            <li>
                <%=t("about_1")%>
            </li>
            <hr>
            <li>
                <%=t("about_2")%>
            </li>
            <hr>
            <li>
                <%=t("about_3")%>
            </li>
            <hr>
            <li>
                <%=t("about_4")%>
            </li>
            <br>
        </ol>
    </div>
</div>

app/views/posts/edit.html.erb
<h1><%=t("e_post")%></h1>

<%= render 'form' %>
<br>
<div  style="text-align:right">
    <x>
        <a href="/posts/<%=@post.id%>?locale=<%= I18n.locale %>"><i class="fa fa-eye fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;<%=t("show")%></a>
    </x>
</div>
</div>

app/views/posts/like.js.erb
$('#<%=@post.id%>').html('<%= link_to "", unlike_post_path(@post), class:"fa fa-heart fa-lg",style:"text-decoration: none;",remote: :true, method: :put %>')

app/views/posts/new.html.erb
<!--<h1><%=t("n_post")%></h1>-->
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<!--<h1><%=t("post")%></h1>-->
<div class="panel panel-default kayit_divi container" style="width:100%;">
  <% if @post.title!=""%>
    <div class="panel-heading" style="overflow:auto;word-wrap:break-word;">
      <h2 style="color:black;text-align:center;"><%=@post.title%></h2>
    </div>
  <% else %>
    <br>
  <%end%> 
    <div class="panel-body" style="overflow:auto;word-wrap:break-word;">
      <div class="row" style="padding:1%;">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <% if @post.image? %>
            <%= image_tag @post.image.url(:medium), :style => 'display:block;margin:auto;' %>
          <% else %>
            <strong><%=t("n_img")%>.</strong>
          <% end %>
        </div>
      </div>
      <hr style="background-color:black;border-color:black;">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6" style="text-align:left;">
          <% if @post.image? %>
            <strong><%=t("f_name")%> : </strong><%=@post.image_file_name%><br>
            <strong ><%=t("f_type")%> : </strong><%=@post.image_content_type%>
          <% else %>
            <strong><%=t("f_name")%> : </strong>-------<br>
            <strong ><%=t("f_type")%> : </strong>-------
          <% end %>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6" style="text-align:right;">
          <strong ><%=t("c_date")%> : </strong> <%=@post.created_at%><br>
          <strong ><%=t("u_date")%> : </strong><%=@post.updated_at%>
        </div>
      </div>
      <hr  style="background-color:black;border-color:black;">
      <% if @post.title!=""%>
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
          <textarea class="form-control" rows="15" id="index" readonly style="resize:none;color:black;background-color:white;border-color:lightblue;"><%=@post.msg%></textarea>
        </div>
      </div>
      <hr  style="background-color:black;border-color:black;">
      <%end%>
      
      
      
      <% if user_signed_in? %>
      
        <%=render 'comments/form'%>
      
      <% end %>
      
      
      
      
      <hr  style="background-color:black;border-color:black;">
      
      <div id=comments>
        <%@comments.each do |c|%>
          <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
              <%=image_tag c.user.image.url(:mini),style:"border-radius:1em;" if @post.user.image?%>
            </div>
            
            <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
              <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <b>
                    <%=c.user.name%> <%=c.user.surname%> <%=c.id%>
                  </b>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <%=c.bdy%>
                </div>
              </div>
              <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <x>
                  <% if user_signed_in? %>
                    <% if current_user.id==c.user_id %>
                      <a href="/posts/<%=@post.id%>/comments/<%=c.id%>?locale=<%= I18n.locale %>" style="text-decoration: none;padding:0.5%;border:0;">
                        <i class="fa fa-eye"></i>
                      </a>
                      
                      <a href="/posts/<%=@post.id%>/comments/<%=c.id%>/edit?locale=<%= I18n.locale %>"  style="text-decoration: none;padding:0.5%;border:0;"> 
                        <i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
                      </a>
                      
                      <a data-confirm="<%=t("p_data_confirm")%>?" rel="nofollow" data-method="delete" 
                      href="/posts/<%=@post.id%>/comments/<%=c.id%>?locale=<%= I18n.locale %>" style="text-decoration: none;padding:0.5%;border:0;">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                      </a>
                    <% end %>
                  <% end %>
                  </x>
                </div>
              </div>
            </div>
          </div>
          <br>
        <%end%> 
      </div>
    <%if @likeds.count>0%>  
      <i class="fa fa-heart fa-lg" style="color:red"></i>&nbsp;<i><%=@likeds.count%></i>&nbsp;&nbsp;
      <% @likeds.each do |l|%>
        <%=l.user.name%>
      <% end %>
    <%end%>
    </div>
    
    <div class="panel-footer" style="padding:1%;">
      <div class="row">
        <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2" id="<%=@post.id%>">  
        <% if user_signed_in? %>
          <%if Like.where(user:current_user, post:@post).count>0%>                             
	          <%= link_to "", unlike_post_path(@post), class:"fa fa-heart fa-lg",style:"text-decoration: none;",remote: :true, method: :put %>                          
          <%else%>                            
 	          <%= link_to "", like_post_path(@post), class:"fa fa-heart-o fa-lg",style:"text-decoration: none;",remote: :true, method: :put %>                          
          <%end%>
        <%end%>
        </div>
        
        <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10" style="text-align:right;">
          <% if @post.image? %>
            <y>
              <a href=<%=@post.image.url(:orginal)%> download title="<%=t("download_link")%>." data-toggle="tooltip" data-placement="left">
                <i class="fa fa-download fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;<%=t("download")%>
              </a>
            </y>
          <% end %>
          
          <x>
            <a></a>
            <% if user_signed_in? %>
              <% if current_user.id==@post.user_id %>
                <a href="/posts/<%=@post.id%>/edit?locale=<%= I18n.locale %>">
                  <!--title="<%=t("edit_link")%>." data-toggle="tooltip" data-placement="left"-->
                  <i class="fa fa-pencil fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;<%=t("edit")%>
                </a>
                <a data-confirm="<%=t("p_data_confirm")%>?" rel="nofollow" data-method="delete" href="/posts/<%=@post.id%>?locale=<%= I18n.locale %>">
                  <!--title="<%=t("destroy_link")%>." data-toggle="tooltip" data-placement="left"-->
                  <i class="fa fa-trash fa-lg" aria-hidden="true"></i>&nbsp;&nbsp;<%=t("destroy")%>!
                </a>
              <% end %>
            <% end %>
          </x>
        </div>
      </div>
    </div>
</div>

app/views/posts/unlike.js.erb
$('#<%=@post.id%>').html('<%= link_to "", like_post_path(@post), class:"fa fa-heart-o fa-lg",style:"text-decoration: none;",remote: :true, method: :put %>')